# Listado de Productos *METODO GET*
GET http://localhost:4000/api/products

###

# Crear un Producto *METODO POST*
POST http://localhost:4000/api/products
Content-Type: application/json
Accept-Language:en-US,en;q=0.5

{
    "name":"Producto cpu",
    "price":-300  
}

###
